# Generated by Django 2.2.24 on 2021-11-23 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackpackBadgeShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=254)),
                ('source', models.CharField(default='unknown', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackpackCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('share_hash', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, default=None, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BackpackCollectionBadgeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackpackCollectionShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=254)),
                ('source', models.CharField(default='unknown', max_length=254)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpack.BackpackCollection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
