# A dockerized badgr-server stack for development
version: '3.3'
services:

  # this container mirrors in the app code and runs the django dev server
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev.api  
    depends_on:
      - "db"
      - "memcached"
    command: bash -c "/badgr_server/manage.py runserver 0.0.0.0:8000 && /usr/local/bin/dockerinit"

    volumes:
      - ./dev/shm:/dev/shm     
      - ./apps:/badgr_server/apps
      - ./manage.py:/badgr_server/manage.py
      - ./.docker/etc/settings_local.dev.py:/badgr_server/apps/mainsite/settings_local.py

    networks:
      - badgr
#    environment: 
#      - VSCODE_DEBUGGER=True  

    ports:
      - "8000:8000"
      - "3000:3000"

  # this container runs memcached
  memcached:
    image: 'bitnami/memcached:latest'
    expose:
      - "11211"
    networks:
      - badgr

  # this container runs mysql (database)
  db:
    image: mysql:5.6.39
    ports:
      - "3306:3306"
    volumes:
      - badgr_server_dev_db:/var/lib/mysql:rw
      - ./.docker/etc/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=password"
    expose:
      - "3306"
    networks:
      - badgr

#   sqlite:
#    image: nouchka/sqlite3:latest
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./db/:/root/db/

networks:
  badgr:
    driver: bridge

volumes:
  badgr_server_dev_db:
