# Generated by Django 2.2.24 on 2021-10-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0026_auto_20200817_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='token',
            field=models.TextField(default=False),
        ),
    ]
