# Generated by Django 2.2.24 on 2021-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0027_badgeuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='did',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='wallet_id',
            field=models.TextField(default=False),
        ),
    ]
