# Generated by Django 2.2.24 on 2021-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0028_auto_20211001_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='credential_issuer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='issuer_did',
            field=models.TextField(default=False),
        ),
    ]
