# Generated by Django 2.2.24 on 2021-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0029_auto_20211007_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeuser',
            name='credential_issuer',
        ),
        migrations.RemoveField(
            model_name='badgeuser',
            name='issuer_did',
        ),
        migrations.AlterField(
            model_name='badgeuser',
            name='did',
            field=models.TextField(blank=True, default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badgeuser',
            name='token',
            field=models.TextField(blank=True, default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badgeuser',
            name='wallet_id',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
