# Generated by Django 2.2.24 on 2021-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0059_remove_issuer_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='issuer_did',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='cred_ex_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='issuer_did',
            field=models.TextField(blank=True, default=False, max_length=254, null=True),
        ),
    ]
