# Generated by Django 2.2.24 on 2021-11-23 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import issuer.models
import jsonfield.fields
import mainsite.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('image_hash', models.CharField(blank=True, default='', max_length=72)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('source', models.CharField(default='local', max_length=254)),
                ('source_url', models.CharField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, upload_to='uploads/badges')),
                ('image_preview', models.FileField(blank=True, null=True, upload_to='uploads/badges')),
                ('issuer_did', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('criteria_url', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('criteria_text', models.TextField(blank=True, null=True)),
                ('expires_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('expires_duration', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default=None, max_length=254, null=True)),
                ('old_json', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Badge classes',
            },
            bases=(mainsite.mixins.ResizeUploadedImage, mainsite.mixins.ScrubUploadedSvgImage, mainsite.mixins.PngImagePreview, models.Model),
        ),
        migrations.CreateModel(
            name='BadgeClassAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('target_name', models.TextField()),
                ('target_url', models.CharField(max_length=2083)),
                ('target_description', models.TextField(blank=True, default=None, null=True)),
                ('target_framework', models.TextField(blank=True, default=None, null=True)),
                ('target_code', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeClassExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeClassTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('source', models.CharField(default='local', max_length=254)),
                ('source_url', models.CharField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('issued_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_identifier', models.CharField(db_index=True, max_length=768)),
                ('recipient_type', models.CharField(choices=[('email', 'email'), ('openBadgeId', 'openBadgeId'), ('telephone', 'telephone'), ('url', 'url')], default='email', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='uploads/badges')),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('revocation_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cred_ex_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('acceptance', models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unaccepted', max_length=254)),
                ('hashed', models.BooleanField(default=True)),
                ('salt', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('narrative', models.TextField(blank=True, default=None, null=True)),
                ('old_json', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BadgeInstanceBakedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obi_version', models.CharField(max_length=254)),
                ('image', models.FileField(blank=True, upload_to=issuer.models._baked_badge_instance_filename_generator)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeInstanceEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('evidence_url', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('narrative', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeInstanceExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('source', models.CharField(default='local', max_length=254)),
                ('source_url', models.CharField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/issuers')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('issuer_did', models.TextField(blank=True, default=False, max_length=254, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('old_json', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=(mainsite.mixins.ResizeUploadedImage, mainsite.mixins.ScrubUploadedSvgImage, mainsite.mixins.PngImagePreview, models.Model),
        ),
        migrations.CreateModel(
            name='IssuerStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('staff', 'Staff')], default='staff', max_length=254)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuerExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
