# Generated by Django 2.2.24 on 2021-11-23 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer', '0001_initial'),
        ('mainsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='badgrapp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.BadgrApp'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuer',
            name='staff',
            field=models.ManyToManyField(through='issuer.IssuerStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeinstanceextension',
            name='badgeinstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeInstance'),
        ),
        migrations.AddField(
            model_name='badgeinstanceevidence',
            name='badgeinstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeInstance'),
        ),
        migrations.AddField(
            model_name='badgeinstancebakedimage',
            name='badgeinstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeInstance'),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='badgeclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeinstances', to='issuer.BadgeClass'),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer'),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeclasstag',
            name='badgeclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeClass'),
        ),
        migrations.AddField(
            model_name='badgeclassextension',
            name='badgeclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeClass'),
        ),
        migrations.AddField(
            model_name='badgeclassalignment',
            name='badgeclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeClass'),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeclasses', to='issuer.Issuer'),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='issuerstaff',
            unique_together={('issuer', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='badgeinstance',
            index_together={('recipient_identifier', 'badgeclass', 'revoked')},
        ),
    ]
